### ISSUE TITLE
Epic / 0.7 / Forcefields

### ISSUE THREAD

**Issue by trisyoungs** [projectdissolve/dissolve#328]
### Focus
Addresses critical issues and improvements to forcefield implementation and behaviour, driven by user requests.

### Tasks
- [x] #195 Can't geometry minimise charged species
- [x] #326 Add CosN torsion terms
- [x] #327 Improper term energies are not always calculated
