### ISSUE TITLE
Epic / Documentation 0.7

### ISSUE THREAD

**Issue by trisyoungs** [projectdissolve/dissolve#469]
### Focus
Provide basic information on all aspects in the code to accompany 0.7 release.

### Tasks
- [x] #205 Add example SCARF script to documentation
- [x] #209 Clarify restart file role and usage
- [x] #204 Missing section describing download / compilation / installation
- [x] #197 Glossary of terms
- [x] #172 Argon - difficulty  looking for manipulation 
- [x] #176 Add tip for 'Instrument Broadening' in tutorial
- [x] #180 Explain coordinate system 
- [x] #182 Document how to add bonds after drawing atoms
- [x] #184 Benzene -  Distance/Angle range confusion 
- [x] #168 Make AppImage executable
